"""
Hybrid Data Manager: PostgreSQL primary, Excel fallback, auto-sync.
"""
import os
import json
from datetime import datetime, date
from pathlib import Path
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from config import (
    DATABASE_URL, EXCEL_FILE, EXCEL_PASSWORD, DATA_DIR,
    DEFAULT_DUE_DAY, DEFAULT_GRACE_DAYS, DEFAULT_LATE_FEE_TYPE,
    DEFAULT_LATE_FEE_AMOUNT, DEFAULT_MAX_LATE_FEE, DEFAULT_WORKING_DAYS,
    DEFAULT_HALF_DAY_FACTOR
)

# ── Excel Headers ─────────────────────────────────────────
EXCEL_HEADERS = {
    "Students": [
        "Admission No", "Student Name", "Father Name", "Mother Name",
        "Class", "Section", "Roll No", "DOB", "Gender", "Mobile",
        "Address", "Admission Date", "Session", "Transport",
        "Status", "Created At", "Updated At"
    ],
    "Fee_Transactions": [
        "Receipt No", "Date", "Time", "Admission No", "Student Name",
        "Class", "Section", "Fee Type", "Month", "Amount", "Late Fee",
        "Payment Mode", "Transaction No", "Remarks", "Received By"
    ],
    "Fee_Structure": [
        "Class", "Admission Fee", "Tuition Fee", "Transport Fee",
        "Exam Fee", "Annual Fee", "Other Fee"
    ],
    "Users": [
        "Username", "Password Hash", "Role", "Status",
        "Failed Attempts", "Locked", "Permissions",
        "Security Q1", "Security A1", "Security Q2", "Security A2",
        "Security Q3", "Security A3", "Created At", "Updated At"
    ],
    "Audit_Log": ["Date", "Time", "Username", "Action", "Details"],
    "Settings": ["Key", "Value"],
    "Staff": [
        "Staff ID", "Name", "Designation", "Department", "Mobile",
        "Joining Date", "Basic Salary", "Allowances", "Status",
        "Created At", "Updated At"
    ],
    "Staff_Attendance": [
        "Date", "Staff ID", "Staff Name", "Status", "Remarks",
        "Marked By", "Approved By", "Approval Status"
    ],
    "Salary_Records": [
        "Month", "Staff ID", "Staff Name", "Working Days", "Present",
        "Absent", "Leave", "Half Day", "LOP", "Basic Salary",
        "Allowances", "Deductions", "Advance", "Net Salary",
        "Generated At", "Generated By"
    ],
}


def _style_sheet(ws):
    fill = PatternFill("solid", fgColor="173F73")
    font = Font(color="FFFFFF", bold=True)
    thin = Side(style="thin", color="D9E2F3")
    for cell in ws[1]:
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = Border(bottom=thin)
    ws.freeze_panes = "A2"
    for col_cells in ws.columns:
        max_len = 0
        for c in col_cells:
            try:
                max_len = max(max_len, len(str(c.value or "")))
            except:
                pass
        ws.column_dimensions[get_column_letter(col_cells[0].column)].width = min(max(max_len + 3, 12), 35)


def _protect_sheet(ws):
    try:
        ws.protection.sheet = True
        ws.protection.set_password(EXCEL_PASSWORD)
    except:
        pass


def init_excel():
    """Create Excel file with all sheets if not exists."""
    if EXCEL_FILE.exists():
        return
    wb = Workbook()
    wb.remove(wb.active)
    for name, headers in EXCEL_HEADERS.items():
        ws = wb.create_sheet(name)
        for col, h in enumerate(headers, 1):
            ws.cell(1, col, h)
        _style_sheet(ws)
        _protect_sheet(ws)
    # Default settings
    settings = wb["Settings"]
    for k, v in [
        ("School Name", "BLUE DIAMOND PUBLIC SCHOOL"),
        ("School Address", "Dadri, Gautam Budh Nagar, Uttar Pradesh"),
        ("Academic Session", "2026-27"),
        ("Session Start Month", "4"),
        ("Currency", "INR"),
        ("Receipt Prefix", "BDPS"),
        ("Due Day", str(DEFAULT_DUE_DAY)),
        ("Grace Days", str(DEFAULT_GRACE_DAYS)),
        ("Late Fee Enabled", "Yes"),
        ("Late Fee Type", DEFAULT_LATE_FEE_TYPE),
        ("Late Fee Amount", str(DEFAULT_LATE_FEE_AMOUNT)),
        ("Late Fee Percent", "2"),
        ("Max Late Fee", str(DEFAULT_MAX_LATE_FEE)),
        ("Max Login Attempts", "3"),
        ("Working Days Per Month", str(DEFAULT_WORKING_DAYS)),
        ("Salary LOP Deduction", "Yes"),
        ("Half Day Count", str(DEFAULT_HALF_DAY_FACTOR)),
    ]:
        settings.append([k, v])
    wb.save(EXCEL_FILE)


def excel_to_dicts(sheet_name):
    """Read a sheet from Excel as list of dicts."""
    if not EXCEL_FILE.exists():
        return []
    wb = load_workbook(EXCEL_FILE, read_only=True, data_only=True)
    if sheet_name not in wb.sheetnames:
        wb.close()
        return []
    ws = wb[sheet_name]
    rows = list(ws.iter_rows(values_only=True))
    wb.close()
    if not rows:
        return []
    headers = list(rows[0])
    result = []
    for row in rows[1:]:
        if not any(v is not None for v in row):
            continue
        item = {}
        for i, h in enumerate(headers):
            item[h] = row[i] if i < len(row) else ""
        result.append(item)
    return result


def clear_excel_sheet(sheet_name):
    """Clear all data rows from a sheet (keep headers)."""
    if not EXCEL_FILE.exists():
        return
    wb = load_workbook(EXCEL_FILE)
    if sheet_name not in wb.sheetnames:
        wb.close()
        return
    ws = wb[sheet_name]
    if ws.max_row > 1:
        ws.delete_rows(2, ws.max_row)
    wb.save(EXCEL_FILE)
    wb.close()


def append_to_excel(sheet_name, row_dict):
    """Append a dict as a row to Excel sheet."""
    init_excel()
    wb = load_workbook(EXCEL_FILE)
    ws = wb[sheet_name]
    headers = [c.value for c in ws[1]]
    row = [row_dict.get(h, "") for h in headers]
    ws.append(row)
    wb.save(EXCEL_FILE)
    wb.close()


def write_excel_sheet(sheet_name, records):
    """Overwrite a sheet with records."""
    init_excel()
    wb = load_workbook(EXCEL_FILE)
    ws = wb[sheet_name]
    if ws.max_row > 1:
        ws.delete_rows(2, ws.max_row)
    headers = [c.value for c in ws[1]]
    for rec in records:
        ws.append([rec.get(h, "") for h in headers])
    wb.save(EXCEL_FILE)
    wb.close()


class HybridDataManager:
    """
    Manages data across PostgreSQL and Excel with automatic failover.
    """

    def __init__(self, app=None, db=None):
        self.app = app
        self.db = db
        self.pg_available = False
        self._check_pg()

    def _check_pg(self):
        """Test PostgreSQL connection."""
        if not self.app:
            return False
        try:
            with self.app.app_context():
                self.db.session.execute(self.db.text("SELECT 1"))
                self.pg_available = True
                return True
        except Exception:
            self.pg_available = False
            return False

    def get_all(self, model, order_by=None):
        """Get all records from PG or Excel."""
        if self.pg_available:
            try:
                q = model.query
                if order_by is not None:
                    q = q.order_by(order_by)
                return [r.to_dict() for r in q.all()]
            except Exception:
                self.pg_available = False
        # Excel fallback
        sheet = self._sheet_for_model(model)
        return excel_to_dicts(sheet)

    def get_one(self, model, **filters):
        """Get one record."""
        if self.pg_available:
            try:
                return model.query.filter_by(**filters).first()
            except Exception:
                self.pg_available = False
        return None

    def save(self, obj):
        """Save a model instance to PG or queue for sync."""
        if self.pg_available:
            try:
                self.db.session.add(obj)
                self.db.session.commit()
                return obj
            except Exception:
                self.db.session.rollback()
                self.pg_available = False
        # Queue for Excel
        return obj

    def delete(self, obj):
        if self.pg_available:
            try:
                self.db.session.delete(obj)
                self.db.session.commit()
                return True
            except Exception:
                self.db.session.rollback()
                self.pg_available = False
        return False

    def _sheet_for_model(self, model):
        mapping = {
            'Student': 'Students',
            'FeeTransaction': 'Fee_Transactions',
            'FeeStructure': 'Fee_Structure',
            'User': 'Users',
            'AuditLog': 'Audit_Log',
            'Setting': 'Settings',
            'Staff': 'Staff',
            'Attendance': 'Staff_Attendance',
            'SalaryRecord': 'Salary_Records',
        }
        return mapping.get(model.__name__, model.__tablename__)

    # ── Sync: Excel → PostgreSQL ──────────────────────────
    def sync_excel_to_pg(self):
        """
        Push all Excel data to PostgreSQL, then clear Excel.
        Called when PG becomes available.
        """
        if not self.pg_available:
            return {'success': False, 'message': 'PostgreSQL not available'}

        from models import (
            Student, FeeTransaction, FeeStructure, User,
            AuditLog, Setting, Staff, Attendance, SalaryRecord
        )

        counts = {}
        try:
            # Students
            students = excel_to_dicts("Students")
            for s in students:
                if not Student.query.filter_by(admission_no=s.get("Admission No")).first():
                    obj = Student(
                        admission_no=s.get("Admission No", ""),
                        student_name=s.get("Student Name", ""),
                        father_name=s.get("Father Name", ""),
                        mother_name=s.get("Mother Name", ""),
                        class_name=s.get("Class", ""),
                        section=s.get("Section", ""),
                        roll_no=s.get("Roll No", ""),
                        dob=s.get("DOB", ""),
                        gender=s.get("Gender", ""),
                        mobile=s.get("Mobile", ""),
                        address=s.get("Address", ""),
                        admission_date=s.get("Admission Date", ""),
                        session=s.get("Session", "2026-27"),
                        transport=s.get("Transport", "No"),
                        status=s.get("Status", "Active"),
                    )
                    self.db.session.add(obj)
            counts['students'] = len(students)

            # Fee Transactions
            txs = excel_to_dicts("Fee_Transactions")
            for t in txs:
                if not FeeTransaction.query.filter_by(receipt_no=t.get("Receipt No")).first():
                    obj = FeeTransaction(
                        receipt_no=t.get("Receipt No", ""),
                        date=t.get("Date", ""),
                        time=t.get("Time", ""),
                        admission_no=t.get("Admission No", ""),
                        student_name=t.get("Student Name", ""),
                        class_name=t.get("Class", ""),
                        section=t.get("Section", ""),
                        fee_type=t.get("Fee Type", ""),
                        month=t.get("Month", ""),
                        amount=float(t.get("Amount") or 0),
                        late_fee=float(t.get("Late Fee") or 0),
                        payment_mode=t.get("Payment Mode", ""),
                        transaction_no=t.get("Transaction No", ""),
                        remarks=t.get("Remarks", ""),
                        received_by=t.get("Received By", ""),
                    )
                    self.db.session.add(obj)
            counts['fee_transactions'] = len(txs)

            # Users
            users = excel_to_dicts("Users")
            for u in users:
                if not User.query.filter_by(username=u.get("Username")).first():
                    obj = User(
                        username=u.get("Username", ""),
                        password_hash=u.get("Password Hash", ""),
                        role=u.get("Role", "Data Entry"),
                        status=u.get("Status", "Active"),
                        failed_attempts=int(u.get("Failed Attempts") or 0),
                        locked=str(u.get("Locked", "No")).lower() in ("yes", "true", "1"),
                        permissions=u.get("Permissions", "{}"),
                    )
                    self.db.session.add(obj)
            counts['users'] = len(users)

            # Staff
            staff = excel_to_dicts("Staff")
            for s in staff:
                if not Staff.query.filter_by(staff_id=s.get("Staff ID")).first():
                    obj = Staff(
                        staff_id=s.get("Staff ID", ""),
                        name=s.get("Name", ""),
                        designation=s.get("Designation", ""),
                        department=s.get("Department", ""),
                        mobile=s.get("Mobile", ""),
                        joining_date=s.get("Joining Date", ""),
                        basic_salary=float(s.get("Basic Salary") or 0),
                        allowances=float(s.get("Allowances") or 0),
                        status=s.get("Status", "Active"),
                    )
                    self.db.session.add(obj)
            counts['staff'] = len(staff)

            # Attendance
            att = excel_to_dicts("Staff_Attendance")
            for a in att:
                if not Attendance.query.filter_by(
                    date=a.get("Date"), staff_id=a.get("Staff ID")
                ).first():
                    obj = Attendance(
                        date=a.get("Date", ""),
                        staff_id=a.get("Staff ID", ""),
                        staff_name=a.get("Staff Name", ""),
                        status=a.get("Status", "Present"),
                        remarks=a.get("Remarks", ""),
                        marked_by=a.get("Marked By", ""),
                        approved_by=a.get("Approved By", ""),
                        approval_status=a.get("Approval Status", "Approved"),
                    )
                    self.db.session.add(obj)
            counts['attendance'] = len(att)

            # Settings
            settings = excel_to_dicts("Settings")
            for s in settings:
                existing = Setting.query.filter_by(key=s.get("Key")).first()
                if existing:
                    existing.value = str(s.get("Value", ""))
                else:
                    self.db.session.add(Setting(key=s.get("Key"), value=str(s.get("Value", ""))))
            counts['settings'] = len(settings)

            self.db.session.commit()

            # Clear Excel after successful sync
            for sheet in ["Students", "Fee_Transactions", "Staff", "Staff_Attendance"]:
                clear_excel_sheet(sheet)

            return {'success': True, 'counts': counts}

        except Exception as e:
            self.db.session.rollback()
            return {'success': False, 'message': str(e)}